### ISSUE TITLE
Create a "Driver Station"

### ISSUE THREAD

**Issue by shmishtopher** [AndersonRobotics/Tools#1]
We should write some "driver station" software, for driving and testing robots without a controller.  We would also need to come up with a standard for driver <-> robot comms.

**Comment by shmishtopher** [comment]
What operating systems are ya'll running?  What platforms do we need to support?
@MichaelBenvenuto 
@Samcfuchs 
@sparklypig 
@riverpup525

**Comment by MichaelBenvenuto** [comment]
Windows is my primary, linux is what i run on my second desktop at home, but, since OSX shares the generic POSIX libraries, all we would need to do for OSX support is change `__linux__` to `__unix__`
